image_angle = random(360);
if (sprite_index = sprSmallCrate) size = 1; 
else size = 2;
if (size = 1) maxhp = round(random_range(5,9));
else maxhp = round(random_range(10,16));
hp = maxhp;
hitfade = 0;
soundcanplay = 0;
stopdash = 0;
ImmuneToBomb = 0;
