if (!eId.HasDiffuser) exit;
de = instance_create(x,y,oExplosion);
de.diffuser = 1;
de.sprite_index = sprShockwave;
de.image_xscale = 0.2;
de.image_yscale = 0.2;
de.image_alpha = 0.3;
de.hittype = 6;
de.myid = myid;
if (myid = Weapons.wSpazerBeam) or (myid = Weapons.wPhazonBeam) de.numexp = 6;
